### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by brianach** [brianach/wells#1]
EPIC: About page

As a **user** I can **view an about page** so that **I can learn more about the app or website**

**Acceptance Criteria**

- [ ] - User can view and about page

**Tasks**

- [ ] Task 1: Design and implement an about page
- [ ] Task 2: Add an image to the page
