### ISSUE TITLE
User account registration

### ISSUE THREAD

**Issue by brianach** [brianach/wells#19]
EPIC: Account registration and usage

As a site user I want to be able to register so that I can post comments

**Acceptance Criteria**

1. User can register an account
2. User can login
3. User can logout

**Tasks**

- [x] Task 1: Add code and modal to handle account registration
- [x] Task 2: Add code and modal to handle account login
- [x] Task 3: Add code and modal to handle account logout
