### ISSUE TITLE
Add well locations

### ISSUE THREAD

**Issue by brianach** [brianach/wells#21]
EPIC: Map Locations

As a staff user I can create location records so that markers will be available on the map

**Acceptance Criteria**

Form/model has title, townland, county, coordinates and cures
Staff User can create a map entry

**Tasks**

- [x] Task 1: Design model , view and form
- [x] Task 3: Implement functionality
- [x] Task 4: Test functionality
