### ISSUE TITLE
Create Posts

### ISSUE THREAD

**Issue by brianach** [brianach/wells#22]
EPIC: Create Posts

As a staff user I can create a post so that users can get information about a well

**Acceptance Criteria**

Model has title, address, image and  content.
Staff User can add as much content as they like
Staff User can preview the information provided before submission
Staff User can edit the information 

**Tasks**

- [x] Create the model, view and template
- [x] Implement the code
- [x] Test the code
