### ISSUE TITLE
UAT - Tablet

### ISSUE THREAD

**Issue by brianach** [brianach/wells#24]
EPIC: UAT

As a **user** I can **access all available features on a tablet ** so that **UAT Tablet passes**

**Acceptance Criteria**

Home page:

- Menu items all working.

> About Page is accessible

> Map Page is accessible

> Authentication is accessible

> Posts are accessible

- Map page

>  Location markers are visible

> Location markers open when clicked

- Location Markers

> Post link works for links with posts

> Google map link works

> Google map location is correct

- Authentication

> Login modal works if not logged in

> Logout modal works if logged in

> Register modal works if no account exists

**Tasks**

- [x] Home page opens
    - [x] Menu items all working.
        - [x] About Page is accessible
        - [x] Map Page is accessible
        - [x] Authentication is accessible
        - [x] Posts are accessible

- [x] Map page
    - [x] Location markers are visible
    - [x] Location markers open when clicked
    - [x]  Map is scrollable
    - [x] Map is zoomable
    - [x] Header and footer remain in place while scrolling map

    - [x] Location popup actions
        - [x] Post link works for links with posts
        - [x] Google map link works
        - [x] Google map location is correct

- [x] Authentication
    - [x] Login modal works if not logged in
    - [x] Logout modal works if logged in
    - [x] Register modal works if no account exists
