### ISSUE TITLE
Create Agile Project

### ISSUE THREAD

**Issue by brianach** [brianach/wells#3]
EPIC: <Create Agile Project>

As a **project owner** I can **add issues and tasks** so that **I can manage the project**

**Acceptance Criteria**

- [x] - Owner can manage the project timeline
- [x] - Owner can add tasks and issues
- [x] - Owner can prioritize tasks and issues
- [x] - Owner can add milestones

**Tasks**

- [x] Task 1: Create issue template
- [x] Task 2: Create labels and milestones
- [x] Task 3: Create Issues
- [x] Task 4: Create Project
