### ISSUE TITLE
Install all the required libraries

### ISSUE THREAD

**Issue by brianach** [brianach/wells#4]
EPIC: <Install project libraries>

As a **developer** I can **install all the libraries** so that **I can test the barebones functionality**

**Acceptance Criteria**

- [ ] - MVP libraries all installed

**Tasks**

- [x] Task 1: Create workspace
- [ ] Task 2: Install libraries
- [ ] Task 3: Build requirements.txt
- [ ] Task 4: Configure SQL

**Comment by brianach** [comment]
- [ ] Install Django and gunicorn:	pip3 install 'django<4' gunicorn
- [ ] Install supporting libraries:	pip3 install dj_database_url==0.5.0 psycopg2
- [ ] Install Cloudinary Libraries	"pip3 install dj3-cloudinary-storage
- [ ] pip3 install urllib3==1.26.15"
- [ ] Create requirements file	pip3 freeze --local > requirements.txt
- [ ] Create Project (codestar 2021)	"django-admin startproject <PROJ_NAME . >
- [ ] Create App (blog)	python3 manage.py startapp APP_NAME
- [ ] Add to installed apps  
                        INSTALLED_APPS = [
                            …
                            'APP_NAME',
                        ]
