### ISSUE TITLE
Deploy project to Heroku

### ISSUE THREAD

**Issue by brianach** [brianach/wells#5]
EPIC: <Deploy project to Heroku>

As a **developer ** I can **deploy to Heroku** so that **I can test everything at the beginning to ensure deployment works**

**Acceptance Criteria**

- [x] - Heroku app is created
- [x] - ElephantSQL DB is created
- [x] - Cloudinary is connected
- [x] - Template folders and Procfile are setup
- [x] - Heroku configured
- [x] - Deployed to Heroku
- [x] - App tested working on Heroku

**Tasks**

- [x] Task 1: Create app on heroku
- [x] Task 2: Create ElephantSQL DB
- [x] Task 4: Configure Cloudinary
- [x] Task 3: Configure all necessary settings
- [x] Task 5: Create template folders and add Procfile
- [x] Task 6: Deploy app
- [x] Task 7: Run deployment

**Comment by brianach** [comment]
Create env.py
Add DATABASE_URL and SECRET_Key to env.py
Ensure env.py is in the .gitignore file

**Comment by brianach** [comment]
- [ ] Add DISABLE_COLLECTSTATIC : 1 temporary variable in Heroku 
- [ ] Add the cloudinary library to settings.py
          'cloudinary.storage' above 'django.contrib.staticfiles'
          'cloudinary' under  'django.contrib.staticfiles'

**Comment by brianach** [comment]
Procfile has a capital 'P' and the contents are web: gunicorn <APP>.wsgi where APP is your app name

**Comment by brianach** [comment]
Heroku failed with error **_"at=error code=H10 desc="App crashed" method=GET path"_**
 
Reason was that the Cloudinary url value in heroku settings contained CLOUDINARY_URL: at the beginning
