### ISSUE TITLE
Set up Admin Backend

### ISSUE THREAD

**Issue by brianach** [brianach/wells#6]
EPIC: <Admin page>

As a **superuser ** I can **manage posts and accounts** so that **I can administer the site effectively**

**Acceptance Criteria**

1. Create Database Diagram
2. Create Database Model
3. Create Superuser
4. Create Staff user

-
**Tasks**

- [x] Task 1: Create Database Diagram
- [x] Task 2: Create Database Model
- [x] Task 3: Create Superuser
- [x] Task 4: Create Staff user
