### ISSUE TITLE
Create Map Page

### ISSUE THREAD

**Issue by brianach** [brianach/wells#7]
EPIC: <Documentation>

As a **coder** I can **create the map** so that **I can test map page funcitonality**

**Acceptance Criteria**

- [x] - Well model created
- [x] - Map view created
- [x] - Well admin view registered

**Tasks**

- [x] - Create Well model 
- [x] - Create Map view 
- [x] - Register the view in admin
