### ISSUE TITLE
Create and test location popup

### ISSUE THREAD

**Issue by brianach** [brianach/wells#9]
EPIC: <Create and test location popup>

As a **coder** I can **clock a location icon** so that **I can test popup functionality**

**Acceptance Criteria**

- [x] Popup appears when the location icon is clicked

**Tasks**

- [x] Create HTML popup template
- [x] Add JS to trigger popup
- [x] Test popup contains location data
